### ISSUE TITLE
Feature-request: Auto-transmit past N transmissions on reload

### ISSUE THREAD

**Issue by captdeaf** [anephenix/dashku#17]
Hi - Thanks for dashku, it's a nifty piece of work!

I am using dashku with webscreensaver, so every time a machine goes idle, it starts showing my dashboard. Unfortunately: a number of my data scripts are "poll once an hour", so my widgets show default data for quite a while when first viewed.

Is there a way, or can you add a way, for a widget to pull the past X bits of data? (Or am I missing something in the docs that enables this?)

e.g:

this.on('load', function(data){
  this.retransmit(10); /* Request retransmission of the past 10 transmissions for this widget. */
});

(Also, With this, it may also be wise to add a timestamp to every json structure pushed to the API, for timed-out data such as alert messages/notifications.)

**Comment by paulbjensen** [comment]
I'm going to close this issue. Pull requests with code changes are welcome and will be considered.
