### ISSUE TITLE
Issue loading widgets in multiple browsers

### ISSUE THREAD

**Issue by vanlee1987** [anephenix/dashku#40]
Hi Paul,

I am having some issues that may relate to error handling (or maybe an issue with my environment which I've done my best to rule out).  The D3 Bullet widget throws "Uncaught ReferenceError: bullet is not defined" and the rest of the widgets fail to load in Chrome and IE.  In FF, I get a ws connection interrupted message and some widgets also fail to load.  I pushed an install onto AWS so you can check it out:

With Bullet Widget:
http://ec2-54-214-228-237.us-west-2.compute.amazonaws.com:3000/#?dashboard=535838f773e0501b3a2eb9f2

Without Bullet Widget:
http://ec2-54-214-228-237.us-west-2.compute.amazonaws.com:3000/#?dashboard=5358428392fc54ab3cf135e5

Should I be using a different version of Node than the latest stable build (0.10.26)?  Do I need to do more with my environment?  Currently, I have stuck to just installing redis, mongodb, and node.

Thank you,
Van

**Comment by paulbjensen** [comment]
Hi Van,

The Bullet widget issue was fixed a while back. To update your widget templates, pull the latest version of Dashku from Github, then run this command on your machine:

    npm run populateWidgetTemplates

Then, when you create a new bullet widget, it should work just fine.

Regards,

Paul Jensen
