### ISSUE TITLE
Easy pulling and automatic full screen?

### ISSUE THREAD

**Issue by Zyles** [anephenix/dashku#41]
Immense thank you for this project. I have been looking for a good dashboard project for a while.

Looking at your video it is very focused on the developer which is nice. Is there a function to add pulling of data in an easy way or do you need to use javascript there as well?

Is it possible to force automatic browser full screen upon dashboard loading?

I hope to see more pre-made standardized widgets similar to those that exist on Geckoboard in the future.

Thanks!

**Comment by paulbjensen** [comment]
Closing for now, as mentioned elsewhere pull requests are welcome and will be considered.
