### ISSUE TITLE
Dashboard rotating

### ISSUE THREAD

**Issue by Zyles** [anephenix/dashku#42]
A great feature would be able to rotate dashboards. So if you create 5 of them, then you go into a rotator settings page and set a rotation for 3 of your dashboards. You also define rotate time. This generates an unique link for this rotation which you visit with your browser.

This way you can create multiple rotations with different dashboards.

Right now you would have to resort to using browser extensions such as revolver tabs etc. But it would be nice to have this built in so it requires less of a setup on the browser end for the monitor machine and resets on reboots etc.

**Comment by paulbjensen** [comment]
Hi Zyles,

I'm going to close this for now. Pull requests are welcome and will be considered.
