### ISSUE TITLE
broadcasting data to multiple widgets

### ISSUE THREAD

**Issue by afrozl** [anephenix/dashku#44]
I really like the way the dashing dashboard framwework (https://github.com/Shopify/dashing) allows for data to be sent to any widget that has a data-id attribute set to a specific value. 

On the other hand, I prefer the node.js and socketstream foundation of Dashku. I wonder if we could leverage socketstream's pub/sub events to achieve the same functionality.

As an example, could we have widgets subscribe to a specific channel as described in the docs?:

req.session.channel.subscribe('bignumber1')

and then use that channel to push the data to all widgets 'listening'?

 This would be really powerful if we also used an external event transport.

**Comment by paulbjensen** [comment]
Closing the issue. Pull requests are welcome and will be considered.
