### ISSUE TITLE
Could you please help me in integrating any of the below mentioned graph as a widget in Dashku

### ISSUE THREAD

**Issue by ajgupta42** [anephenix/dashku#56]
Hi,

Could you please help me in integrating any of the below mentioned graph in widget of Dashku?
http://nvd3.org/livecode/index.html#codemirrorNav
I am trying to add Pie chart & Line Chart into Dashku but i am getting nothing but a blank widget.

**Comment by paulbjensen** [comment]
Hi AJ,

Please pull the latest version of Dashku from github, and run this command:

    npm run populateWidgetTemplates

Then add the widgets from there.
